### ISSUE TITLE
SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by kingtianbao** [GalaxySciTech/js-particles#2]
/root/js-particles/blockchain.js:67
      if (tx?.coninbase) {
             ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/js-particles/miner.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by GalaxySciTech** [comment]
looks module not download 

could you pls run `yarn` again ?

**Comment by kingtianbao** [comment]
Do you need a cpu or gpu?

**Comment by GalaxySciTech** [comment]
- ensure you nodejs version 
- ensure you installed the depencies

**Comment by kingtianbao** [comment]
That's fine. Do you use gpu or cpu for this mining?

**Comment by kingtianbao** [comment]
Do you just need to change the minerAddress for.env.example?

**Comment by GalaxySciTech** [comment]
copy your .env.example to .env 
only change minerAddress

gpu and cpu both is ok

**Comment by kingtianbao** [comment]
total 664
drwxr-xr-x  6 root root   4096 Oct  1 07:42 ./
drwx------  1 root root   4096 Oct  1 07:38 ../
-rw-r--r--  1 root root    113 Oct  1 07:42 .env
-rw-r--r--  1 root root    113 Oct  1 07:38 .env.example
drwxr-xr-x  8 root root    163 Oct  1 07:37 .git/
drwxr-xr-x  3 root root     28 Oct  1 07:37 .github/
-rw-r--r--  1 root root     18 Oct  1 07:37 .gitignore
-rw-r--r--  1 root root   1218 Oct  1 07:37 README.md
-rw-r--r--  1 root root   6281 Oct  1 07:37 blockchain.js
-rw-r--r--  1 root root    470 Oct  1 07:37 config.js
drwxr-xr-x  2 root root     57 Oct  1 07:37 db/
-rw-r--r--  1 root root 591269 Oct  1 07:37 image.png
-rw-r--r--  1 root root   2787 Oct  1 07:37 miner.js
drwxr-xr-x 81 root root   4096 Oct  1 07:39 node_modules/
-rw-r--r--  1 root root   1133 Oct  1 07:37 p2p.js
-rw-r--r--  1 root root    166 Oct  1 07:37 package.json
-rw-r--r--  1 root root    382 Oct  1 07:37 utils.js
-rw-r--r--  1 root root      0 Oct  1 07:37 wallet.js
-rw-r--r--  1 root root  25972 Oct  1 07:37 yarn.lock

**Comment by kingtianbao** [comment]
![image](https://github.com/GalaxySciTech/js-particles/assets/73821694/c51c41b6-d26f-4b8b-9a59-287242cbcfd4)
I have no balance in my account

**Comment by GalaxySciTech** [comment]
can you use this curl --location 'https://p2p.particles.digital/get-balance?address=${address}' to check your wallet?

**Comment by kingtianbao** [comment]
I am not sure if I have filled in the address correctly,Your tutorial is not very clear

**Comment by GalaxySciTech** [comment]
for example

https://p2p.particles.digital/get-balance?address=0xD7c7c1E83a1d8E30f5Da542F99d7b9bDD896600e

i think its work 

unless your minerAddress is not yours in your .env file

**Comment by kingtianbao** [comment]
![image](https://github.com/GalaxySciTech/js-particles/assets/73821694/add0b98f-52d4-400a-a541-43c2a6754075)
Is that right？There is only.env.example in your file, I need to make a copy as.env, right?

**Comment by GalaxySciTech** [comment]
only .env is useful

**Comment by kingtianbao** [comment]
Is he using a GPU or a CPU by default, how do I tell

**Comment by GalaxySciTech** [comment]
default is cpu

**Comment by kingtianbao** [comment]
How do I switch to a GPU

**Comment by GalaxySciTech** [comment]
The program does not support GPU now, I misunderstood you earlier

**Comment by kingtianbao** [comment]
I feel like my CPU is only starting one thread, how can I increase it

**Comment by GalaxySciTech** [comment]
`npm install -g pm2`
`pm2 start miner -i max`

**Comment by kingtianbao** [comment]
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:3666
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:2069:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3666
}

Node.js v20.5.1

**Comment by GalaxySciTech** [comment]
please cheng to  

> node:internal/errors:496 ErrorCaptureStackTrace(err); ^
> 
> Error: listen EADDRINUSE: address already in use 127.0.0.1:3666 at Server.setupListenHandle [as _listen2] (node:net:1872:16) at listenInCluster (node:net:1920:12) at GetAddrInfoReqWrap.doListen [as callback] (node:net:2069:7) at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) { code: 'EADDRINUSE', errno: -98, syscall: 'listen', address: '127.0.0.1', port: 3666 }
> 
> Node.js v20.5.1

this one will fix next version

**Comment by kingtianbao** [comment]
> `npm install -g pm2` `pm2 start miner.js -i max`

Do I run this so I don't have to run any other commands? For example, node miner.js

**Comment by GalaxySciTech** [comment]
> > `npm install -g pm2` `pm2 start miner.js -i max`
> 
> Do I run this so I don't have to run any other commands? For example, node miner.js

yeah

**Comment by kingtianbao** [comment]
My digging didn't get me anything
